server:
  port: 8080

logging:
  level:
    root: warn
    org.springframework.web: warn
    me.taling.live: debug
    me.taling.live.infra.feign: debug

redis:
  host: taling-live-prod-redis.9wvxas.0001.apn2.cache.amazonaws.com
  port: 6379
  publish-host: taling-message-redis.9wvxas.0001.apn2.cache.amazonaws.com
  publish-port: 6379


queue:
  lesson-create: live-classroom-create-request-queue

# 내부(탈잉)서버 endpoints
internal-endpoints:
  taling-web: https://taling.me
  taling-live-front: https://live.taling.me
  taling-message: https://ch.taling.me
  taling-stream: https://stream.taling.me

# external-endpoints:

services:
  reference:
    aws:
      app-key: 51f3bd1d647cfd3c22242cdaa092e11e
      secret-key: 180c52ddfa7067677004481adba6c6dead4131fc8ffcf9915ed9bff6c7fd67cf
    taling-web:
      app-key: 51f3bd1d647cfd3c22242cdaa092e11e
      secret-key: 180c52ddfa7067677004481adba6c6dead4131fc8ffcf9915ed9bff6c7fd67cf
    live-recorder:
      app-key: 51f3bd1d647cfd3c22242cdaa092e11e
      secret-key: 180c52ddfa7067677004481adba6c6dead4131fc8ffcf9915ed9bff6c7fd67cf

aws:
  ivs:
    channel-type: STANDARD
    channel-latency-mode: LOW
    authorized: false
    recording-configuration-arn: arn:aws:ivs:us-east-1:869998438082:recording-configuration/jzODIOwIJTtV
    origin-source:
      prefix: https://ivs-live-recordings-prod.s3.amazonaws.com
      postfix: /media/hls/master.m3u8

feign:
  message:
    client-id: FWDNuKfsx_K161PBfwWC27oHspce55bwWUMrwPKbDRFV2oCMIx
    client-secret: z6d1Hh0zONgeb1HHZ8KULr47oBc8S95QGNuk-Q5gdxtpIbXa_n

cookie-name: TalingSessId

# bot ecs
bot:
  ecs-cluster-arn: arn:aws:ecs:ap-northeast-2:869998438082:cluster/taling-live-bot
  security-groups: sg-0ffea97096b99cbb0
  subnets: subnet-0f2c2d86d6138b594,subnet-0f508889b0aa5d512,subnet-03c60455adaea579e

springfox:
  documentation:
    swagger-ui:
      enabled: false