PUT {{host}}/internals/space/2_H9OVD4PUvcJmaFmXRi6
Authorization: {{token}}
Content-Type: application/json

{
  "title": "테스트2",
  "expiredAt": "2021-11-29T08:34:13.768Z",
  "managers": [],
  "referenceId": "string",
  "startedAt": "2021-11-29T08:34:13.768Z",
  "tutor": {
    "id": 408697,
    "nickname": "nickname",
    "profileImageUrl": "https://taling.me",
    "profileThumbnailUrl": "https://taling.me"
  },
  "users": [
    {
      "id": 546565,
      "nickname": "https://taling.me",
      "profileImageUrl": "https://taling.me",
      "profileThumbnailUrl": "https://taling.me"
    },
    {
      "id": 546566,
      "nickname": "https://taling.me",
      "profileImageUrl": "https://taling.me",
      "profileThumbnailUrl": "https://taling.me"
    }
  ]
}